export const STATE_DISTRICT_DATA = [
  { state: 'Andhra Pradesh', districts: ['Anantapur', 'Guntur', 'Visakhapatnam'] },
  { state: 'Arunachal Pradesh', districts: ['Itanagar', 'Tawang', 'Ziro'] },
  { state: 'Assam', districts: ['Dibrugarh', 'Guwahati', 'Silchar'] },
  { state: 'Bihar', districts: ['Gaya', 'Muzaffarpur', 'Patna'] },
  { state: 'Chhattisgarh', districts: ['Bilaspur', 'Durg', 'Raipur'] },
  { state: 'Delhi', districts: ['Central Delhi', 'North Delhi', 'South Delhi'] },
  { state: 'Goa', districts: ['North Goa', 'South Goa'] },
  { state: 'Gujarat', districts: ['Ahmedabad', 'Rajkot', 'Surat'] },
  { state: 'Haryana', districts: ['Faridabad', 'Gurugram', 'Panipat'] },
  { state: 'Himachal Pradesh', districts: ['Kangra', 'Shimla', 'Solan'] },
  { state: 'Jharkhand', districts: ['Bokaro', 'Dhanbad', 'Ranchi'] },
  { state: 'Karnataka', districts: ['Bengaluru Urban', 'Mysuru', 'Udupi'] },
  { state: 'Kerala', districts: ['Ernakulam', 'Kozhikode', 'Thiruvananthapuram'] },
  { state: 'Madhya Pradesh', districts: ['Bhopal', 'Gwalior', 'Indore'] },
  { state: 'Maharashtra', districts: ['Mumbai', 'Nagpur', 'Pune'] },
  { state: 'Odisha', districts: ['Cuttack', 'Khordha', 'Sambalpur'] },
  { state: 'Punjab', districts: ['Amritsar', 'Ludhiana', 'Patiala'] },
  { state: 'Rajasthan', districts: ['Jaipur', 'Jodhpur', 'Udaipur'] },
  { state: 'Tamil Nadu', districts: ['Chennai', 'Coimbatore', 'Madurai'] },
  { state: 'Telangana', districts: ['Hyderabad', 'Nizamabad', 'Warangal'] },
  { state: 'Uttar Pradesh', districts: ['Kanpur Nagar', 'Lucknow', 'Varanasi'] },
  { state: 'Uttarakhand', districts: ['Dehradun', 'Haridwar', 'Nainital'] },
  { state: 'West Bengal', districts: ['Darjeeling', 'Howrah', 'Kolkata'] },
];